/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>


/*  Header for class Sieve  */

#ifndef _Included_Sieve
#define _Included_Sieve

#define HSieve ClassSieve
typedef struct ClassSieve {
#pragma pack(push,4)
	long MSReserved;
#define Sieve_F 3.2
#pragma pack(pop)
} ClassSieve;

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) long __cdecl Sieve_CountPrimes (struct HSieve *, struct HArrayOfByte *);
#ifdef __cplusplus
}
#endif

#endif  /* _Included_Sieve */
