<div class="contents" >
<table  width=70% align=left>
<thead>
<tr>
   <td><H5>ABOUT THE CORPORATE MEDIA LIBRARY</H5></td>
</tr>
</thead>
<tbody>
<tr>
   <td>The Fitch & Mather Corporate Media Library has been developed as an example of
      Windows DNA development for a small to medium&ndash;sized company. Questions or comments
      should be sent to the <a href="mailto:bdgfeed@microsoft.com">BackOffice Developer's Guide (BDG)</a>. 
      The site and its components were created exclusively using the Visual InterDev 6.0 tools.
      Visit the <a href="http://www.fmcorp.com">official Fitch & Mather site</a> for more information
      and samples.<p>
   </td>
</tr>
</tbody>
</div>
