# ----------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------

all :
         cd AFCBean
         $(CMDLINE)
         cd ..\Calendar
         $(CMDLINE)
         cd ..\Event
         $(CMDLINE)
         cd ..\Invoke
         $(CMDLINE)
         cd ..\JBrowser
         $(CMDLINE)
         cd ..\JCalendar
         $(CMDLINE)
         cd ..\JChart
         $(CMDLINE)
         cd ..\orgtree
         $(CMDLINE)
         cd ..\SafeArray
         $(CMDLINE)
         cd ..\SampleBean
         $(CMDLINE)
         cd ..
