Proj = permain
dll = 1

!include <bkoffice.mak>

ObjList = $(ObjDir)\permain.obj

linkflags = $(linkflags) -Def:perfmain.Def

All: $(ObjDir)\$(Proj).dll

$(ObjDir)\$(Proj).dll: $(ObjList)
