//****************************************************************************
//  Module:     Chappy.EXE
//  File:       Chtitems.h
//              
//
//  Copyright (c) Microsoft Corporation 1996-1997
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
// PARTICULAR PURPOSE.
//****************************************************************************

#if !defined(AFX_CHTITEMS_H__C473B984_FFA9_11D0_AD6F_00C04FC29DE5__INCLUDED_)
#define AFX_CHTITEMS_H__C473B984_FFA9_11D0_AD6F_00C04FC29DE5__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChatItems wrapper class

class CChatItems : public COleDispatchDriver
{
public:
	CChatItems() {}		// Calls COleDispatchDriver default constructor
	CChatItems(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChatItems(const CChatItems& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetAssociatedType();
	void SetAssociatedType(LPCTSTR lpszNewValue);
	VARIANT GetValidItems();
	long GetItemValid(LPCTSTR ItemName);
	VARIANT GetItem(LPCTSTR ItemName);
	void SetItem(LPCTSTR ItemName, const VARIANT& newValue);
	void InvalidateItem(LPCTSTR ItemName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHTITEMS_H__C473B984_FFA9_11D0_AD6F_00C04FC29DE5__INCLUDED_)
