# Microsoft Developer Studio Generated NMAKE File, Based on VCExplore.dsp
".\comadmin_i.c" : "..\..\..\..\include\comadmin.idl"
	<<tempfile.bat 
	@echo off 
	midl ..\..\..\..\include\comadmin.idl /out ..\..\..\..\include
	nmake /a /f prjmakefile
<<
