; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CCustom1Dlg
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "ICSAgentWiz.h"

ClassCount=2
Class1=CCustom1Dlg
Class2=CCustom2Dlg

ResourceCount=2
Resource1=IDD_CUSTOM2
Resource2=IDD_CUSTOM1


[CLS:CCustom1Dlg]
Type=0
HeaderFile=cstm1dlg.h
ImplementationFile=cstm1dlg.cpp
Filter=D
BaseClass=CAppWizStepDlg
VirtualFilter=dWC
LastObject=CCustom1Dlg

[DLG:IDD_CUSTOM1]
Type=1
Class=CCustom1Dlg
ControlCount=2
Control1=IDC_EXCHANGE_TREE,SysTreeView32,1350635831
Control2=IDC_STATIC,static,1342308352

[CLS:CCustom2Dlg]
Type=0
HeaderFile=cstm2dlg.h
ImplementationFile=cstm2dlg.cpp
Filter=D

[DLG:IDD_CUSTOM2]
Type=1
Class=CCustom2Dlg
ControlCount=1
Control1=IDC_STATIC,static,1342308352

