cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\Components\HBNews
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBNews.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\Components\HBExchange
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBExchange.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\Components\HBInstitution
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBInstitution.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\Components\HBNotify
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBNotify.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\HBFeed
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBFeed.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\HBTradeStation
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBTradeStation.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\XML\HBXMLServer
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBXMLServer.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\XML\HBXMLClient
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBXMLClient.vbp
pause
cd D:\mssdk\Samples\COM\Application_Samples\Hanson_Brothers\HBInstall
"D:\Program Files\Microsoft Visual Studio\VB98\VB6.exe" HBInstall.vbp
pause
