//=========================================================================
// Resource.H
//
// Copyright (C) 1986-1996.  Microsoft Corp.  All Rights Reserved.
//
// Purpose:
//    Generated by Microsoft Developer Studio
//=========================================================================

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by postsmpl.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_POSTSMTYPE                  129
#define ICO_File                        137
#define IDD_FOLDERPICKER                140
#define ICO_MdbOpen                     146
#define ICO_Mdb                         147
#define ICO_FolderOpen                  149
#define ICO_Folder                      150
#define ICO_Exchange                    152
#define ICO_DefaultMdbOpen              153
#define ICO_DefaultMdb                  154
#define IDC_TREEVIEW                    1056
#define IDD_SUMMARYINFO                 1057
#define IDC_FileName                    1058
#define IDC_Directory                   1059
#define IDC_Title                       1060
#define IDC_Subject                     1061
#define IDC_Author                      1062
#define IDC_Keywords                    1063
#define IDC_Comments                    1064
#define ID_FILE_POSTDOC                 32771
#define ID_FILE_POSTMSG                 32774
#define ID_FILE_SUM_INFO                32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
