//=========================================================================
// stdafx.cpp
//
// Copyright (C) 1986-1996.  Microsoft Corp.  All Rights Reserved.
// 
//
// Purpose:
//   source file that includes just the standard includes
//	PostSmpl.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information

//=========================================================================


#include "stdafx.h"

