//--stdafx.cpp----------------------------------------------------------------
//
// source file that includes just the standard includes
//	mbxserv.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information
//
// Copyright (C) Microsoft Corp. 1986-1996.  All Rights Reserved.
//----------------------------------------------------------------------------

#include "stdafx.h"

