#----------------------------------------------------------------------------
# Description:
#   Makefile for DSExport.Exe
#
# Copyright (C) Microsoft Corp. 1986-1998.  All Rights Reserved.
#----------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = DsExport

LibList = DApi.Lib EdkUtils.Lib EdkDebug.Lib

!include <BkOffice.Mak>

all:    $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj
