# ----------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------

all :
         cd AFCDetect\src
         $(CMDLINE)
         cd ..\..\BandsnMenus\src
         $(CMDLINE)
         cd ..\..\Buttons\src
         $(CMDLINE)
         cd ..\..\FxShapes\src
         $(CMDLINE)
         cd ..\..\FxTextures\src
         $(CMDLINE)
         cd ..\..\JNotepad\src
         $(CMDLINE)
         cd ..\classes
         $(CMDLINE)
         cd ..\..\JTreeVue\src
         $(CMDLINE)
         cd ..\..\Lists\src
         $(CMDLINE)
         cd ..\..\LoanCalc\src
         $(CMDLINE)
         cd ..\..\Puzzle15\src
         $(CMDLINE)
         cd ..\..\Scrolls\src
         $(CMDLINE)
         cd ..\..\Statics\src
         $(CMDLINE)
         cd ..\..\Viewers\src
         $(CMDLINE)
         cd ..\..\Win32ResSupport
         $(CMDLINE)
         cd ..
