#---------------------------------------------------------------------------
# Description:
#   Make file to generate RestTest.exe
#
# Copyright (C) Microsoft Corp. 1986-1998. All Rights Reserved.
#---------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

LibList = EDBBCli.lib

Proj = RestTest

!include <BkOffice.Mak>

all:  $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj
