#----------------------------------------------------------------------------
# Description:
#   Makefile for Track.Exe
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#----------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = Track

LibList = RpcRt4.Lib

ObjList = $(@R).Obj

!Include <BkOffice.Mak>

all:     $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(ObjList)
