
/******************************************************************************\
********************************************************************************
* Filename: StdAfx.h
*
* Description:

		stdafx.h : include file for standard system include files,
		or project specific include files that are used frequently,
		but are changed infrequently


*
* This file is provided as part of the Microsoft Transaction Server
* Software Development Kit
*
*THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT 
*WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, 
*INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
*OF MERCHANTABILITY AND/OR FITNESS FOR A  PARTICULAR 
*PURPOSE.
*
* Copyright (C) 1997 Microsoft Corporation, All rights reserved
********************************************************************************
\******************************************************************************/

#if !defined(AFX_STDAFX_H__F523E419_8485_11D0_B170_00AA00BA3258__INCLUDED_)
#define AFX_STDAFX_H__F523E419_8485_11D0_B170_00AA00BA3258__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#define STRICT

#include <list>
#include <map>
using namespace std;
#pragma warning( disable : 4786) // disable the warning "identifier was truncated to '255' characters in the debug information" generated by STL

#define SafeRelease(pUnk) {if (pUnk){pUnk -> Release();pUnk = NULL; }}

#define _WIN32_WINNT 0x0500
#define _ATL_APARTMENT_THREADED


#include <atlbase.h>
//You may derive a class from CComModule and use it if you want to override
//something, but do not change the name of _Module
extern CComModule _Module;
#include <atlcom.h>

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__F523E419_8485_11D0_B170_00AA00BA3258__INCLUDED)
