#---------------------------------------------------------------------------
# Description:
#   Make file to generate EdkCfg.Lib
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#---------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = EdkCfg

ObjList = $(@D)\CfgNotif.Obj $(@R).Obj

!Include <BkOffice.Mak>

all: $(ObjDir)\$(Proj).Lib

$(ObjDir)\$(Proj).Lib: $(ObjList)
