<% Dim Border %>
<% Border = 0 %>

<html>
<head>
<title>ILS Server List Page</title>
</head>
<body bgcolor="#FFFFFF" link=#000080 vlink=#004080>
<table cellspacing="0" width="100%">
	<tr>
		<td width="288"><img SRC="images/B_NETMEETING.gif" alt="Microsoft NetMeeting" height="67" width="288"></td>
		<td align="CENTER"><b><font face="Arial, Helvetica" size=5>Other ILS Servers</font></b></td>
	</tr>
</table>
<br>
<br>
<br>
<br>
<br>
<center>
<table cellspacing=0 cellpadding=7 width="400" border=1>
	<tr>
		<td><font face="Arial, Helvetica" size="3"><b><nobr>Server Name</nobr></b></font></td>
		<td><font face="Arial, Helvetica" size="3"><b>Description</b></font></td>
	</tr>

	<tr>
		<td valign="TOP">
		<font face="Arial, Helvetica" size="2">
		<a href="http://ils.microsoft.com" target="_top">ils.microsoft.com</a><br>
		<a href="http://ils1.microsoft.com" target="_top">ils1.microsoft.com</a><br>
		<a href="http://ils2.microsoft.com" target="_top">ils2.microsoft.com</a><br>
		<a href="http://ils3.microsoft.com" target="_top">ils3.microsoft.com</a><br>
		<a href="http://ils4.microsoft.com" target="_top">ils4.microsoft.com</a><br>
		<a href="http://ils5.microsoft.com" target="_top">ils5.microsoft.com</a><br>
		</font>
		</td>
		<td valign="TOP"><font face="Arial, Helvetica" size="2">Public NetMeeting directory servers operated by Microsoft.</font></td>
	</tr>

	<tr>
		<td valign="TOP"><font face="Arial, Helvetica" size="2"><a href="http://ils.four11.com" target="_top">ils.four11.com</a></font></td>
		<td valign="TOP"><font face="Arial, Helvetica" size="2">Public NetMeeting directory server operated by <a href="http://www.Four11.com">Four11</a>.</font></td>
	</tr>

	<tr>
		<td valign="TOP"><font face="Arial, Helvetica" size="2"><a href="http://ils.family.four11.com" target="_top">ils.family.four11.com</a></font></td>
		<td valign="TOP"><font face="Arial, Helvetica" size="2">Public NetMeeting directory server operated by <a href="http://www.Four11.com">Four11</a> specifically targeted at family users</font>.</td>
	</tr>

	<tr>
		<td valign="TOP"><font face="Arial, Helvetica" size="2"><a href="http://ils.business.four11.com" target="_top">ils.business.four11.com</a></font></td>
		<td valign="TOP"><font face="Arial, Helvetica" size="2">Public NetMeeting directory server operated by <a href="http://www.Four11.com">Four11</a> specifically targeted at business users.</font></td>
	</tr>

	<tr>
		<td valign="TOP"><font face="Arial, Helvetica" size="2"><i><a href="http://www.netmeet.net/ilslist.htm" target="_top">www.netmeet.net</a></i></font></td>
		<td valign="TOP"><font face="Arial, Helvetica" size="2"><i>A comprehensive list of NetMeeting servers worldwide</i>.</font></td>
	</tr>
</table>
<br>&nbsp;
<br>&nbsp;
<br>&nbsp;
</body>
</html>
