<html>
<head>
<title>MS Toolbar</title>
</head>
<body bgcolor="#FFFFFF" topmargin="0" leftmargin="0"> 
<!--TOOLBAR_START-->
<table width=100% cellpadding=0 cellspacing=0 border=0>
    <tr>
    	<td width=500 rowspan=2 valign=top>
		<font face="Arial, Helvetica" size=1>
		<table width=100% cellpadding=0 cellspacing=0 border=0 bgcolor="#000000">
			<tr>
				<td>
				<a href="http://www.microsoft.com" target="_top">
				<img src="images/home.gif" width=103 height=21 alt="Microsoft Home" border=0>
				</a>
				</td>
				
				<td>				
				<a href="http://www.microsoft.com/products/default.asp?divisionid=10" target="_top">
				<img src="images/prod.gif" width=81 height=21 alt="Products" border=0>
				</a>
				</td>
				
				<td>			
				<a href="http://www.microsoft.com/search/default.asp" target="_top">
				<img src="images/search.gif" width=68 height=21 alt="Search" border=0>
				</a>
				</td>
		
				<td>
				<a href="http://www.microsoft.com/support/" target="_top">
				<img src="images/support.gif" width=74 height=21 alt="Support" border=0>
				</a>
				</td>
		
				<td>
				<a href="http://www.microsoft.com/referral/default.asp" target="_top">
				<img src="images/shop.gif" width=55 height=21 alt="Shop" border=0>
				</a>
				</td>
		
				<td>
				<a href="http://www.microsoft.com/regwiz/regwiz.asp" target="_top">
				<img src="images/write.gif" width=78 height=21 alt="Write Us" border=0>
				</a>
				</td>
		
				<td>
				<img src="images/spacer.gif" width=49 height=21 alt="" border=0>
				</font>
				</td>
			</tr>
		</table>
		</td>
		<td bgcolor="#000000" width=100% height=20>
		</td>
	    <td width=91 rowspan=2 align=right valign=top>
		<font face="Arial, Helvetica" size=1>
		<a href="http://www.microsoft.com" target="_top">
		<img src="images/msft.gif" width=91 height=21 alt="Microsoft Home" border=0></a>
		</font>
		</td>
    </tr>

    <tr>
	    <td bgcolor="#FFFFFF" width=100% height=1>
    	</td>
    </tr>
</table>
<!--TOOLBAR_END-->
</body>
</html>
