#----------------------------------------------------------------------------
# Description:
#   Makefile for EdkTrack.Lib
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#----------------------------------------------------------------------------

USE_EXCHANGE=1

Proj = EdkTrack

ObjList = $(ObjDir)\Track.Obj $(@D)\$(Proj).Obj

!Include <BkOffice.Mak>

all: $(ObjDir)\$(Proj).Lib

$(ObjDir)\$(Proj).Lib: $(@R).Obj
