#---------------------------------------------------------------------------
# Description:
#   Make file to generate XlatDriv.Exe
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#---------------------------------------------------------------------------

USE_EXCHANGE=1

Proj = XlatDriv

!Include <BkOffice.Mak>

ObjList=$(@R).Obj $(@R).Res

all: $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(ObjList)
