/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.LockBytesHelper  */

#ifndef _Included_com_ms_debug_LockBytesHelper
#define _Included_com_ms_debug_LockBytesHelper

struct Classcom_ms_debug_ILockBytes;
#define Hcom_ms_debug_ILockBytes Classcom_ms_debug_ILockBytes

typedef struct Classcom_ms_debug_LockBytesHelper {
#pragma pack(push,1)
	int32_t MSReserved;
#pragma pack(pop)
} Classcom_ms_debug_LockBytesHelper;
#define Hcom_ms_debug_LockBytesHelper Classcom_ms_debug_LockBytesHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) struct HArrayOfByte * __cdecl com_ms_debug_LockBytesHelper_GetBytes (struct Hcom_ms_debug_LockBytesHelper *, struct Hcom_ms_debug_ILockBytes *);
#ifdef __cplusplus
}
#endif
#endif
