/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.EnumRemoteDoubleValueHelper  */

#ifndef _Included_com_ms_debug_EnumRemoteDoubleValueHelper
#define _Included_com_ms_debug_EnumRemoteDoubleValueHelper

struct Classcom_ms_debug_IJavaEnumRemoteDoubleValue;
#define Hcom_ms_debug_IJavaEnumRemoteDoubleValue Classcom_ms_debug_IJavaEnumRemoteDoubleValue

typedef struct Classcom_ms_debug_EnumRemoteDoubleValueHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IJavaEnumRemoteDoubleValue * m_ierdv;
#pragma pack(pop)
} Classcom_ms_debug_EnumRemoteDoubleValueHelper;
#define Hcom_ms_debug_EnumRemoteDoubleValueHelper Classcom_ms_debug_EnumRemoteDoubleValueHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) double __cdecl com_ms_debug_EnumRemoteDoubleValueHelper_GetNext (struct Hcom_ms_debug_EnumRemoteDoubleValueHelper *);
#ifdef __cplusplus
}
#endif
#endif
