/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.RemoteFloatObjectHelper  */

#ifndef _Included_com_ms_debug_RemoteFloatObjectHelper
#define _Included_com_ms_debug_RemoteFloatObjectHelper

struct Classcom_ms_debug_IRemoteFloatObject;
#define Hcom_ms_debug_IRemoteFloatObject Classcom_ms_debug_IRemoteFloatObject

typedef struct Classcom_ms_debug_RemoteFloatObjectHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IRemoteFloatObject * m_irfo;
#pragma pack(pop)
} Classcom_ms_debug_RemoteFloatObjectHelper;
#define Hcom_ms_debug_RemoteFloatObjectHelper Classcom_ms_debug_RemoteFloatObjectHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) float __cdecl com_ms_debug_RemoteFloatObjectHelper_GetValue (struct Hcom_ms_debug_RemoteFloatObjectHelper *);
__declspec(dllexport) void __cdecl com_ms_debug_RemoteFloatObjectHelper_SetValue (struct Hcom_ms_debug_RemoteFloatObjectHelper *, float);
#ifdef __cplusplus
}
#endif
#endif
