/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.ConstantPoolHelper  */

#ifndef _Included_com_ms_debug_ConstantPoolHelper
#define _Included_com_ms_debug_ConstantPoolHelper

struct Classcom_ms_debug_IRemoteClassField;
#define Hcom_ms_debug_IRemoteClassField Classcom_ms_debug_IRemoteClassField

typedef struct Classcom_ms_debug_ConstantPoolHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IRemoteClassField * m_ircf;
#pragma pack(pop)
} Classcom_ms_debug_ConstantPoolHelper;
#define Hcom_ms_debug_ConstantPoolHelper Classcom_ms_debug_ConstantPoolHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) struct HArrayOfByte * __cdecl com_ms_debug_ConstantPoolHelper_GetConstantPoolItem (struct Hcom_ms_debug_ConstantPoolHelper *, long);
#ifdef __cplusplus
}
#endif
#endif
