#----------------------------------------------------------------------------
# Description:
#   Makefile for MBLSampl.exe
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#----------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = MbLSampl

ObjList = $(@R).Obj

!Include <BkOffice.Mak>

all:  $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(ObjList)
