#---------------------------------------------------------------------------
# Description:
#   Make file to generate X400Scr address syntax utility
#
# Copyright (C) Microsoft Corporation 1986 - 1998.  All Rights Reserved.
#---------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = X400Scr

!Include <BkOffice.Mak>

all:  $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe:  $(@R).Obj
