#----------------------------------------------------------------------------
# Description:
#   Makefile for DSImport.Exe
#
# Copyright (C) Microsoft Corporation 1986-1998.  All Rights Reserved.
#----------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = DsImport

!include <BkOffice.Mak>

all:    $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe: $(@R).Obj
