# ----------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------

all :
         cd AutoMode
         $(MAKE)
         cd ..\CdPlayer
         $(MAKE)
         cd ..\FuncPtr1
         $(MAKE)
         cd ..\FuncPtr2
         $(MAKE)
         cd ..\LastErr
         $(MAKE)
         cd ..\OleMode
         $(MAKE)
         cd ..\Pointers
         $(MAKE)
         cd ..\SDump
         $(MAKE)
         cd ..\Simple
         $(MAKE)
         cd ..\Strings
         $(MAKE)
         cd ..\Structs
         $(MAKE)
         cd ..\TBarIcon
         $(MAKE)
         cd ..
