//////////////////////////////////////////////////////////////////////////////////////
//
//  COM+ Admin SDK Sample
//  StdAfx.cpp *rah99*
//
//  This file is provided as part of the COM+ Software Development Kit.
//
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
//  EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
//  OF MERCHANTABILITY AND/OR FITNESS FOR A  PARTICULAR PURPOSE.
//
// Copyright (C) 1999 Microsoft Corporation, All rights reserved
//
///////////////////////////////////////////////////////////////////////////////////////


// stdafx.cpp : source file that includes just the standard includes
//	VCExplore.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information

#include "stdafx.h"



