/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.EnumRemoteBooleanValueHelper  */

#ifndef _Included_com_ms_debug_EnumRemoteBooleanValueHelper
#define _Included_com_ms_debug_EnumRemoteBooleanValueHelper

struct Classcom_ms_debug_IJavaEnumRemoteBooleanValue;
#define Hcom_ms_debug_IJavaEnumRemoteBooleanValue Classcom_ms_debug_IJavaEnumRemoteBooleanValue

typedef struct Classcom_ms_debug_EnumRemoteBooleanValueHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IJavaEnumRemoteBooleanValue * m_ierbv;
#pragma pack(pop)
} Classcom_ms_debug_EnumRemoteBooleanValueHelper;
#define Hcom_ms_debug_EnumRemoteBooleanValueHelper Classcom_ms_debug_EnumRemoteBooleanValueHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) /*boolean*/ long __cdecl com_ms_debug_EnumRemoteBooleanValueHelper_GetNext (struct Hcom_ms_debug_EnumRemoteBooleanValueHelper *);
#ifdef __cplusplus
}
#endif
#endif
