/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.RemoteDoubleObjectHelper  */

#ifndef _Included_com_ms_debug_RemoteDoubleObjectHelper
#define _Included_com_ms_debug_RemoteDoubleObjectHelper

struct Classcom_ms_debug_IRemoteDoubleObject;
#define Hcom_ms_debug_IRemoteDoubleObject Classcom_ms_debug_IRemoteDoubleObject

typedef struct Classcom_ms_debug_RemoteDoubleObjectHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IRemoteDoubleObject * m_irdo;
#pragma pack(pop)
} Classcom_ms_debug_RemoteDoubleObjectHelper;
#define Hcom_ms_debug_RemoteDoubleObjectHelper Classcom_ms_debug_RemoteDoubleObjectHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) double __cdecl com_ms_debug_RemoteDoubleObjectHelper_GetValue (struct Hcom_ms_debug_RemoteDoubleObjectHelper *);
__declspec(dllexport) void __cdecl com_ms_debug_RemoteDoubleObjectHelper_SetValue (struct Hcom_ms_debug_RemoteDoubleObjectHelper *, double);
#ifdef __cplusplus
}
#endif
#endif
