/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.RemoteBooleanObjectHelper  */

#ifndef _Included_com_ms_debug_RemoteBooleanObjectHelper
#define _Included_com_ms_debug_RemoteBooleanObjectHelper

struct Classcom_ms_debug_IRemoteBooleanObject;
#define Hcom_ms_debug_IRemoteBooleanObject Classcom_ms_debug_IRemoteBooleanObject

typedef struct Classcom_ms_debug_RemoteBooleanObjectHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IRemoteBooleanObject * m_irbo;
#pragma pack(pop)
} Classcom_ms_debug_RemoteBooleanObjectHelper;
#define Hcom_ms_debug_RemoteBooleanObjectHelper Classcom_ms_debug_RemoteBooleanObjectHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) /*boolean*/ long __cdecl com_ms_debug_RemoteBooleanObjectHelper_GetValue (struct Hcom_ms_debug_RemoteBooleanObjectHelper *);
__declspec(dllexport) void __cdecl com_ms_debug_RemoteBooleanObjectHelper_SetValue (struct Hcom_ms_debug_RemoteBooleanObjectHelper *, /*boolean*/ long);
#ifdef __cplusplus
}
#endif
#endif
