/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.ms.debug.EnumRemoteFloatValueHelper  */

#ifndef _Included_com_ms_debug_EnumRemoteFloatValueHelper
#define _Included_com_ms_debug_EnumRemoteFloatValueHelper

struct Classcom_ms_debug_IJavaEnumRemoteFloatValue;
#define Hcom_ms_debug_IJavaEnumRemoteFloatValue Classcom_ms_debug_IJavaEnumRemoteFloatValue

typedef struct Classcom_ms_debug_EnumRemoteFloatValueHelper {
#pragma pack(push,1)
	int32_t MSReserved;
	struct Hcom_ms_debug_IJavaEnumRemoteFloatValue * m_ierfv;
#pragma pack(pop)
} Classcom_ms_debug_EnumRemoteFloatValueHelper;
#define Hcom_ms_debug_EnumRemoteFloatValueHelper Classcom_ms_debug_EnumRemoteFloatValueHelper

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) float __cdecl com_ms_debug_EnumRemoteFloatValueHelper_GetNext (struct Hcom_ms_debug_EnumRemoteFloatValueHelper *);
#ifdef __cplusplus
}
#endif
#endif
