#---------------------------------------------------------------------------
# Description:
#   Make file to generate AddrLkUp.Lib
#
# Copyright (C) Microsoft Corp. 1986-1998.  All Rights Reserved.
#---------------------------------------------------------------------------

USE_EXCHANGE=1
console=1

Proj = AddrLkUp

!Include <BkOffice.Mak>

all: $(ObjDir)\$(Proj).Lib

$(ObjDir)\$(Proj).Lib: $(@R).Obj
